### ISSUE TITLE
Documentación Malformada

### ISSUE THREAD

**Issue by Moffinguer** [carlos-bermejo/DP2-Project-C1.04.05#16]
No estuve en la entrega final, sin embargo, puedo asegurar que no está bien hecho el documento Global que se entregó en el primer entregable. Enumero, se deben de arreglar todos para el siguiente entregable:

- [ ] El contenido en el campo de Repository está mal escrito. Redirigir al [Issue](https://github.com/carlos-bermejo/DP2-Project-C1.04.05/issues/15) cuando este esté escrito de manera correcta

**Comment by Moffinguer** [comment]
Como añadido, es recomendable cambiar y crear una carpeta para el siguiente entregable, y separar la documentación entre entregables.

Recomiendo usar una nomenclatura como "DN" siendo "N" el numero del entregable, y guardar ahí toda la documentación referente a ese entregable

**Comment by carzarrei** [comment]
All working
